# Generated by Django 3.0.5 on 2021-03-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('employment', models.CharField(max_length=50)),
                ('emergency_contact_first', models.CharField(max_length=50)),
                ('emerency_contact_last', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_email', models.CharField(max_length=50)),
                ('emergency_contact_relationship', models.CharField(max_length=30)),
                ('insurance', models.CharField(max_length=30)),
                ('medication', models.CharField(max_length=100)),
                ('Do_you_smoke', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('alcohol', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Not a drinker', 'Not a drinker')], default='Unspecified', max_length=500)),
                ('Seen_therapist', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('Contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Unspecified', max_length=500)),
                ('medical_history', models.CharField(choices=[('Cancer', 'Cancer'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes'), ('Learning Disability', 'Learning Disability'), ('ADHD', 'ADHD'), ('Alcoholism', 'Alcoholism'), ('Non-medicated drugs', 'Non_medicated drugs'), ('Mental Illness', 'Mental Illness'), ('Obesity', 'Obesity')], default='Unspecified', max_length=500)),
                ('family_history', models.CharField(choices=[('Cancer', 'Cancer'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes'), ('Learning Disability', 'Learning Disability'), ('ADHD', 'ADHD'), ('Alcoholism', 'Alcoholism'), ('Non-medicated drugs', 'Non_medicated drugs'), ('Mental Illness', 'Mental Illness'), ('Obesity', 'Obesity')], default='Unspecified', max_length=500)),
            ],
        ),
    ]
