# Generated by Django 3.0.5 on 2021-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reason_for_going_to_therapy',
            field=models.CharField(default='Unspecified', max_length=500),
        ),
    ]
