# Generated by Django 3.0.5 on 2021-03-28 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_info', '0002_person_reason_for_going_to_therapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=13)),
                ('occupation', models.CharField(blank=True, default='Occupation', max_length=100)),
                ('emergency_contact_first', models.CharField(blank=True, default='', max_length=50)),
                ('emergency_contact_last', models.CharField(blank=True, default='', max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=15)),
                ('emergency_contact_email', models.CharField(blank=True, default='', max_length=50)),
                ('emergency_contact_relationship', models.CharField(blank=True, default='', max_length=30)),
                ('insurance', models.CharField(max_length=30)),
                ('medication', models.CharField(max_length=100)),
                ('reason_for_going_to_therapy', models.CharField(default='Unspecified', max_length=500)),
                ('Do_you_smoke', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('alcohol', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Not a drinker', 'Not a drinker')], default='Unspecified', max_length=500)),
                ('Seen_therapist', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500)),
                ('Contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Unspecified', max_length=500)),
                ('medical_history', models.CharField(choices=[('Cancer', 'Cancer'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes'), ('Learning Disability', 'Learning Disability'), ('ADHD', 'ADHD'), ('Alcoholism', 'Alcoholism'), ('Non-medicated drugs', 'Non_medicated drugs'), ('Mental Illness', 'Mental Illness'), ('Obesity', 'Obesity')], default='Unspecified', max_length=500)),
                ('family_history', models.CharField(choices=[('Cancer', 'Cancer'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes'), ('Learning Disability', 'Learning Disability'), ('ADHD', 'ADHD'), ('Alcoholism', 'Alcoholism'), ('Non-medicated drugs', 'Non_medicated drugs'), ('Mental Illness', 'Mental Illness'), ('Obesity', 'Obesity')], default='Unspecified', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
